
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: main
    - name: Setup
      run: |
        cd main/box/vagrant/
        chmod +x setup.sh
        ./setup.sh
        cd ../../scripts/
        python3.8 install.py byond default
        python3.8 install.py opendream default
        python3.8 install.py clopendream default
    - name: Run All Curated Tests
      run: |
        cd main/scripts/
        python3.8 test_curation_all.py byond.default opendream.default clopendream.default
    - name: Create Test Reports
      run: |
        cd main/scripts/
        python3.8 test_curation_report.py compile byond.default opendream.default
        python3.8 test_curation_report.py compile byond.default clopendream.default
    - name: Test dir
      run: |
        cd main/
        pwd
        ls
