
name: Compile Test Codebases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
    - name: Setup
      run: |
        box/vagrant/box/vagrant/setup.sh
