
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: main
    - name: Setup
      run: |
        cd main/box/vagrant/
        chmod +x setup.sh
        ./setup.sh
        cd ../../scripts/
        python3.8 install.py byond default
        python3.8 install.py opendream default
        python3.8 install.py clopendream default
