
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: main
    - name: Setup
      run: |
        cd main/box/vagrant/
        ls
